services:
  app:
    image: centolab/centolab-${ENV:-dev}:latest
    container_name: centolab-${ENV:-dev}
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${ENV:-dev}