name: Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push PRD image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/centolab-prd:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/centolab-prd:latest
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.VPS_IP }} "docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/centolab-prd:latest && docker-compose -f /path/to/prd/docker-compose.yml up -d"
    
    - name: Build and push DEV image
      if: github.ref == 'refs/heads/dev'
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/centolab-dev:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/centolab-dev:latest
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.VPS_IP }} "docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/centolab-dev:latest && docker-compose -f /path/to/dev/docker-compose.yml up -d"